# Generated by Django 5.2.8 on 2025-11-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
